_androidTemplateRelPath = "raw/automation/Android.mk"
_androidTemplatePath = _toolsRoot .. "/" .. _androidTemplateRelPath

function getCppsInDirectory(path, relPath)
    local cppList = ""
    for index,fileName in pairs(ls(_toolsRoot .. "/" .. path)) do
        if string.match(fileName, "%.cpp") then
            cppList = cppList .. "                    " .. relPath .. fileName .. " \\\n"
        end
    end
    return cppList
end

local cppList = getCppsInDirectory("src", "")
local androidMakefileData =  io.open(_androidTemplatePath):read('*all')
androidMakefileData = string.gsub(androidMakefileData, "###INSERT_AUTO_GENERATED_CPP_LIST###", cppList)
local androidMakefile = io.open(_toolsRoot .. "/android/jni/Android.mk", "w")
androidMakefile:write("# " .. _autoGeneratedWarningPrefix .. "generate_android.lua\n" .. androidMakefileData)
androidMakefile:close()
